server:
  port: 8080 #更改tomcat端口

spring:
    datasource:
        name: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver
        #基本属性
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
        username: root
        password: root
        #druid相关配置
        #druid:
        filters: stat,wall,log4j,config
        #配置初始化大小/最小/最大
        maxActive: 20
        initialSize: 1
        minIdle: 1
        #获取连接等待超时时间
        maxWait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#          useGlobalDataSourceStat: true
#          web-stat-filter:
#           enabled: true
#           exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid

    thymeleaf:
      cache: false # 开发时关闭缓存,不然没法看到实时页面
      mode: LEGACYHTML5 # 用非严格的 HTML   ,HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
     #prefix: classpath:
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.foxwho.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    #params: count=countSql
    #returnPageInfo: check